### ISSUE TITLE
Request for Getting Started documentation?

### ISSUE THREAD

**Issue by KeetonMartin** [benarnav/arrivals-board#1]
Would appreciate even a little bit of Basic Overview steps. It's been a while since I've worked with microcontrollers, so I'll read some docs before trying to set this up myself. But any nuances or advice you could share would be great!

You still recommend using a Adafruit Matrixportal S3 micocontroller?

What's the process look like of flashing to the chip? Is there some compilation step? Honestly, any links to external docs appreciated too :)

**Comment by KeetonMartin** [comment]
If you don't mind me asking, what pitch display are you using? I see some different options on Adafruit.

**Comment by benarnav** [comment]
I added a setup section at the bottom of the README with hardware and software setup instructions. Hope this helps!

**Comment by KeetonMartin** [comment]
> I added a setup section at the bottom of the README with hardware and software setup instructions. Hope this helps!

Thanks!
