### ISSUE TITLE
Can't quite figure out what the Flask App looks like

### ISSUE THREAD

**Issue by KeetonMartin** [benarnav/arrivals-board#3]
Hey Ben, took a quick look around this repo and I can't seem to find code that goes in the Flask app. Could you maybe help clarify where I should look for that? Or maybe it's in another repo somewhere?

Or do you intend for others to write their own unique flask apps? Could benefit from the clarification as I try to spin this up :) 

thanks,
- Keeton

**Comment by benarnav** [comment]
I updated the setup text to clarify, but it's this file: https://github.com/benarnav/arrivals-board/blob/main/transit_api.py

would love to see it running when you get it set up!
