### ISSUE TITLE
Did the MTA recently stop requiring API Keys?

### ISSUE THREAD

**Issue by KeetonMartin** [benarnav/arrivals-board#4]
As instructed, I went to https://api.mta.info to try to snag an API key. I found this:
<img width="994" alt="Screenshot 2024-06-11 at 7 40 08 PM" src="https://github.com/benarnav/arrivals-board/assets/25427567/bc717ff4-9648-4041-acd5-11b9bc9a9236">
Clicking "Subway Feeds" gives me this:
<img width="994" alt="Screenshot 2024-06-11 at 7 42 03 PM" src="https://github.com/benarnav/arrivals-board/assets/25427567/7bec1bf1-e2cb-4a4b-b697-c1459d351138">

Am I missing something? Is it really true that my flask app needs a key?

**Comment by benarnav** [comment]
turns out MTA no longer requires an api key, I've updated `transit_api.py` and `envier_template.py` to reflect this
