### ISSUE TITLE
Would be cool if could see the timing of next 2-3 trains on that line in that direction

### ISSUE THREAD

**Issue by KeetonMartin** [benarnav/arrivals-board#6]
This is something I started adding on my board, I thought you might appreciate the idea. Maybe I'll clean up my implementation and contribute. If you'd rather do it your own way, please feel free :)

**Comment by benarnav** [comment]
I covered that in the post about the project: https://benjaminarnav.com/posts/arrivals_rgb_display/

Also added instructions for that in the README: https://github.com/benarnav/arrivals-board?tab=readme-ov-file#features

**Comment by KeetonMartin** [comment]
Nice, thanks for the details!
